name: Update TV EN M3U

on:
  schedule:
    - cron: '20 0 * * *' # 00:20 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run M3U Generator
      run: python m3u_generator.py --type tv --lang en

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add tv_en.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update TV EN M3U playlist" && git push)
